### ISSUE TITLE
Декали от душа бесконечно стакаются друг на друге

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/InterBay#102]
Черех 10 минут работы такого душа вокруг места с ним образуется нереальная подлива.
Всё дело в том что декаль мокрого пола почему-то не пропадает со временем, а остается на тайле навсегда.

**Comment by EditorRUS** [comment]
Проблема не в том, что декаль не пропадает, а в том, что на одном месте их сразу несколько образуется.
