### ISSUE TITLE
ШАТТЛЫ И ЛИФТЫ ВОРУЮТ СТЕНЫ

### ISSUE THREAD

**Issue by Spaint** [animusdev/InterBay#113]
При перемещении забирают с собой стены станции, сдвигаясь на 1 тайл

![image](https://user-images.githubusercontent.com/1905699/28226138-e6200132-68f6-11e7-980e-8292c0e61eb9.png)
![image](https://user-images.githubusercontent.com/1905699/28226163-f56e0eb8-68f6-11e7-8b5f-3e1814e7f734.png)

**Comment by OrangeMann** [comment]
Ого, такого еще не видел, а как так получается то?

**Comment by OrangeMann** [comment]
ЕБАНЫЙ В РОТ ЭТОГО ДУСТИНА БЛЯТЬ

**Comment by OrangeMann** [comment]
https://github.com/animusdev/InterBay/commit/cb05cc196e2a8c77020690532bc4aa36baa4052c
