### ISSUE TITLE
Починить коммит боли

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/InterBay#140]
Да, я дебил и залил это коммитом вместо пула:
https://github.com/animusdev/InterBay/commit/f189a0c365b559c10f7da7b90404eae349494c91

**Comment by mattroks101** [comment]
It should be noted that this pain commit merely standardizes the flashing of pain so that it's no longer completely random. The `var/nohalloss` shouldn't do anything, references to it should probably be removed in case they break something.

**Comment by Redict** [comment]
@mattroks101, I think we will leave it like it is for a while
