### ISSUE TITLE
Make knockdown staminaloss a define if it isn't already one. 

### ISSUE THREAD

**Issue by mattroks101** [animusdev/InterBay#175]
I made it a define in English InterBay but right now I think it's  just 120 in a bunch of places here. We should make it a define so it can be changed with more ease.

**Comment by OrangeMann** [comment]
What do you mean?

**Comment by mattroks101** [comment]
I can't edit issues on mobile for some reason. I'll remove all that other crap when I get home.

**Comment by OrangeMann** [comment]
What about Stamina itself, does it needs upgrades?

**Comment by mattroks101** [comment]
Or my screen can just glitch out and make me look crazy. Thanks github.

**Comment by OrangeMann** [comment]
It was me

**Comment by mattroks101** [comment]
I think the only thing stamina itself needs is more things tied to it. A lot that's tied to halloss could be tied to stamina.

**Comment by OrangeMann** [comment]
Stamina regen is not obvious for me, and overall it feels pretty clunky for now.

**Comment by OrangeMann** [comment]
I'll make Milestone for Stamina i guess.

**Comment by mattroks101** [comment]
How do you think that can be improved?

**Comment by OrangeMann** [comment]
How it works now?

**Comment by mattroks101** [comment]
Stamina regenerates passively at 2 per tick. At 100 the bar empties but it still leaves a 20 stamina grace period instead of knocking you down instantly. Jumping, kicking and melee attacks all drain stamina. Melee attacks with an object drain stamina based on the weight class of that object.

**Comment by mattroks101** [comment]
2 per life tick I mean. Not regular tick.

**Comment by OrangeMann** [comment]
How much you need to regen after you exhausted?

**Comment by mattroks101** [comment]
Exhaustion applies a tiny amount of weaken each life tick it's over the maximum exhaustion, which is 120 at the moment. So a little after you get below 120 you'll get back up.

**Comment by OrangeMann** [comment]
So how much man needs to lie on the ground?

**Comment by mattroks101** [comment]
You also can't attack with melee when exhausted either.

**Comment by OrangeMann** [comment]
It's big task so i'll probably make it with many issues.
