### ISSUE TITLE
Решить вопрос с вентиляцией для дронов

### ISSUE THREAD

**Issue by Quardbreak** [animusdev/InterBay#187]
Нужно ли им как мышам ползать по вентиляции? На данный момент они такой особенности не имеют

**Comment by OrangeMann** [comment]
А почему нет? Они всё-таки чинят её, быстрый доступ в любую точку это очень полезно для них.
А абузеров которые юзают дронов не по назначению можно забанить и за другие вещи.

**Comment by MrNoize** [comment]
Действительно, почему отбирать вентиляцию у микромашинок, чинящих станцию? Это же роль последнего плана, когда тебе ничего, кроме инженерии нельзя.
