### ISSUE TITLE
ПРОМАХ В УПОР

### ISSUE THREAD

**Issue by EditorRUS** [animusdev/InterBay#191]
https://vgy.me/SxAqQx.png

Ну это совсем уже пиздец.

**Comment by SweetYogurt** [comment]
[https://youtu.be/gsNVziiTZHI?t=1m30s](url)

**Comment by SweetYogurt** [comment]
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/gsNVziiTZHI/0.jpg)](https://youtu.be/gsNVziiTZHI?t=1m30s)
