### ISSUE TITLE
Почта

### ISSUE THREAD

**Issue by kreeperHLC** [animusdev/InterBay#239]
#### Description of issue
При отправке посылки с адресом, весь мусор начинает идти по этому адресу.

#### Steps to reproduce 
Берешь посылку, указываешь адрес кабинета ХоСа и наслаждаешься тем, что весь мусор теперь идёт в кабинет ХоСа.

**Comment by Error777** [comment]
Чуть позже посмотрю в чем проблема.

**Comment by Error777** [comment]
Проблема вроде как в том, что disposal потом не переключается с режима почты на обычный.
