### ISSUE TITLE
Резист

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/InterBay#245]
Кто там привязывал резист к стамине, зачем было привязывать его напрямую к вербу?
-Простое нажатие на резист отбирает у тебя стамину, даже если тебе не от чего сопротивляться.
-Если тебя кто-то грабает, то своим движением ты создаешь тонну резистов, из-за чего падаешь в обморок надолго.
В общем у кого свободная минутка будет, прикрутите фиксы и кулдаун на вызов действия.

**Comment by OrangeMann** [comment]
Источник проблемы найдете где-то здесь https://github.com/animusdev/InterBay/pull/162

**Comment by Error777** [comment]
Взялся
