### ISSUE TITLE
Добавить фонарики в коробку из сумки.

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/InterBay#36]

**Comment by RandomColonist** [comment]
Их достаточно раскидано по всему судну.

**Comment by OrangeMann** [comment]
Нет

**Comment by RandomColonist** [comment]
Ты меня прости конечно, но нахуя высирать бесполезные и неактуальные идеи? Под видом денерфов бея, что-ли? Ну давай посмотрим:
У офицеров СБ фонарики есть, лежат на вешалке рядом со шкафчиками.
У персонала мостика фонарики есть на складе рядом с мостиком.
У инженеров несколько видов фонариков и мезонные очки доступны в отделе повсеместно.
У медиков не уверен, но вроде тоже лежат на складе, хотя по настоящему он нужен только парамедику.

Если кого-то упустил/для всех остальных - в восьмидесяти процентов шкафчиков с аварийными софтсьютами, масками и баллонами лежат так же аварийные тулбоксы, в которых есть целая рация, флаер/фонарик, лом и ещё какая-то хуйня.

Учитывая всё мной вышесказанное, твоя идея разумнее прозвучит так: "Нужно добавить фонарик в лоадаут за несколько очков, чтоб тот, кому он нужен, мог его спокойно взять, а тот, кому он не нужен, просто не пикал его".

**Comment by Redict** [comment]
А действительно, можно нахуярить фонарик в лоудаут

**Comment by OrangeMann** [comment]
Да

**Comment by RandomColonist** [comment]
Ебать я стену высрал ради фонарика, конечно.
