### ISSUE TITLE
Бафнуть атмос и всё-всё-всё.

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/InterBay#4]

**Comment by Redict** [comment]
Не бафнули еще?

**Comment by RandomColonist** [comment]
Фороновые пожары достаточно робастны, а об стены бьёт вроде нормально. Бафнуть - это чтоб гибало им, что-ли?

**Comment by OrangeMann** [comment]
Отсутствующее давление очень неробастно и говно.
