### ISSUE TITLE
при боли иногда вызываются несуществующие эмоуты, в результате чего появляется сообщение в стиле "Unknown emote 'gnarl'. Type say *help for a list of usable emotes."

### ISSUE THREAD

**Issue by OrangeMann** [animusdev/InterBay#64]

**Comment by MrNoize** [comment]
gnarl вообще в коде нету.

**Comment by OrangeMann** [comment]
Ну вот об этом иссуй.

**Comment by MrNoize** [comment]
Нет, ты не понимаешь... Его вообще нету нигде, даже в коде боли. Посмотрю в конфигах, может там есть.

**Comment by Quardbreak** [comment]
/decl/emote/audible/gnarl
	key ="gnarl"
	emote_message_3p = "USER gnarls and shows its teeth.."
